---
- name: Instalar Apache y dependencias
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2

- name: apache2 service state
  service: name=apache2 state=started enabled=yes
