---
- name: Instalar Redis
  hosts: nosql
  become: yes
  remote_user: root
  become_user: root   
  vars:
    redis_port: 6379
    redis_databases: 1
  roles:
   - nosqlserver



  
  

